#!/bin/bash
set -e

echo 'CC = arm-linux-gcc
STRIP = arm-linux-strip $(BIN_TARGET)
LIB_DIR += $(MAKEROOT)/lib_arm $(MAKEROOT)/libs/libs
COMPILE = $(CC) -muclibc -o $@ $(OBJ) ${addprefix -L,${LIB_DIR}} ${XLINKER}
CFLAGS = -muclibc -c -O2' > evn.mk

if [ "$1" == "g"  ]; then
	echo 'CP_TARGET = cp -u ${BIN_TARGET} ../nand_bak/nand1-2' >> evn.mk
else
	echo 'CP_TARGET = ' >> evn.mk
fi

make
