#!/bin/bash
set -e

if [ "$#" -lt 1 ]; then
	echo 'please input version like "./mk 1 or 2"'
	exit
elif [ "$1" -eq 1 ]; then
	echo '
COMPILE = $(CC) -muclibc -o $@ $(OBJ) ${addprefix -L,${LIB_DIR}} ${XLINKER}
CFLAGS += -muclibc -c -O2
CP_TARGET = cp -u ${BIN_TARGET} ../nand/v1.0/nand1-2/' > evn.mk
make VERSION=1

elif [ "$1" -eq 2 ]; then
	echo '
COMPILE = $(CC) -muclibc -o $@ $(OBJ) ${addprefix -L,${LIB_DIR}} ${XLINKER}
CFLAGS += -muclibc -c -O2 -D_PLATFORM_IS_LINUX_
CP_TARGET = cp -u ${BIN_TARGET} ../nand/v2.0/nand1-2/' > evn.mk
make VERSION=2
fi
